### ISSUE TITLE
Problem for chatlib library

### ISSUE THREAD

**Issue by chrisyxue** [naver-ai/chacha-chatbot#3]
Hi, great work! Could you please tell me how to install the chatlib library used in the **chat.py**  as follows?
```
from chatlib.chatbot import TurnTakingChatSession
from chatlib import cli
```

I find a similar library at https://github.com/python-b5/chatlib.py, but it is not correct.

**Comment by chrisyxue** [comment]
Some Updates.

I downloaded the library from https://github.com/yghokim/chatlib.git, but there is no file named openai_utils.

**Comment by yghokim** [comment]
Hi @chrisyxue, did you set up `poetry` and install dependencies through it, as guided in Readme?

**Comment by chrisyxue** [comment]
Thanks for your reply!

Yes. I followed the instructions from the Readme. 

BTW, according to the poetry file, it shows
"""
[[package]]
name = "chatlib"
version = "0.5.29"
description = "A generalizable Python Chatbot Library"
optional = false
python-versions = "^3.10"
files = []
develop = false

[package.dependencies]
jinja2 = "^3.1.2"
jsonlines = "^3.1.0"
nanoid = "^2.0.0"
openai = "^0.27.8"
pendulum = "^2.1.2"
python-dotenv = "^1.0.0"
yaspin = "^2.3.0"

[package.source]
type = "git"
url = "https://github.com/yghokim/chatlib.git"
reference = "HEAD"
resolved_reference = "b29222d2f65582fe4f2475cc04c99c77977e498f"
"""

where the library source is *https://github.com/yghokim/chatlib.git*

**Comment by yghokim** [comment]
I've updated code in the `main` branch for more robust version tracking.
Can you pull the latest code and try again?

Also, please paste all your console messages so that I can figure out your issue in detail.

**Comment by chrisyxue** [comment]
Hello. Thank you so much for the updates! I can run the chat.py now with the new codes!

However, I got an error like this, and I do not know what 'This event loop is already running' means. Could you please let me how what happened here? Thank you!

`
Please enter your name: zyx
Please enter your age: 10
Start a chat session (id: tcfSa6ciqRNzRKdy76bcl).
Resume chat for session tcfSa6ciqRNzRKdy76bcl
⠙ Thinking...Traceback (most recent call last):
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chat.py", line 34, in <module>
    asyncio.run(cli.run_chat_loop(EmotionChatbotResponseGenerator(user_name=user_name,user_age=user_age)))
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/cli.py", line 39, in run_chat_loop
    await run_chat_loop_from_session(session, initialize=True, commands=commands)
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/cli.py", line 50, in run_chat_loop_from_session
    system_turn = await session.initialize()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chatbot/session.py", line 81, in initialize
    initial_message, metadata, elapsed = await self._response_generator.get_response(self._dialog)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chatbot/response_generator.py", line 44, in get_response
    raise ex
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chatbot/response_generator.py", line 39, in get_response
    response, metadata = await self._get_response_impl(dialog, dry)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/app/response_generator.py", line 174, in _get_response_impl
    msg, metadata = await super()._get_response_impl(dialog, dry)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chatbot/generators/state.py", line 84, in _get_response_impl
    message, metadata, elapsed = await self.__current_generator.get_response(dialog, dry)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chatbot/response_generator.py", line 44, in get_response
    raise ex
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chatbot/response_generator.py", line 39, in get_response
    response, metadata = await self._get_response_impl(dialog, dry)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chatbot/response_generator.py", line 216, in _get_response_impl
    result = await self.__api.run_chat_completion(self.model, messages, self.__params.to_dict())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chat_completion_api.py", line 196, in run_chat_completion
    self.assert_authorize()
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chat_completion_api.py", line 141, in assert_authorize
    self._request_auth_variables_cli()
  File "/Users/xuezhiyu/Desktop/LLMforChildren/chacha-chatbot/chatlib/chat_completion_api.py", line 172, in _request_auth_variables_cli
    answers = prompt(questions)
              ^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/site-packages/questionary/prompt.py", line 78, in prompt
    return unsafe_prompt(questions, answers, patch_stdout, true_color, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/site-packages/questionary/prompt.py", line 223, in unsafe_prompt
    answer = question.unsafe_ask(patch_stdout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/site-packages/questionary/question.py", line 89, in unsafe_ask
    return self.application.run()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 978, in run
    return loop.run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/asyncio/base_events.py", line 660, in run_until_complete
    self._check_running()
  File "/Users/xuezhiyu/opt/anaconda3/envs/chacha/lib/python3.12/asyncio/base_events.py", line 619, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
⠋ Thinking...
`

**Comment by yghokim** [comment]
Did you run setup.py and put your OpenAI API Key properly? It seems that an authorization routine runs during the chat process and causes an error.
